services:
  journeydb:
    image: postgres:16
    environment:
      POSTGRES_DB: journeydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "9876:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
